# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Trigger the action on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Use a recent LTS version of Node.js

      - name: Install dependencies
        run: npm install

      - name: Build slides
        run: npm run build -- --base /android-key-attestation/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The folder the action should deploy

